version: '3'
services:
  django:
    build:
      context: ./testserver
      dockerfile: Dockerfile
    container_name: deploy-app
    volumes:
      - ./testserver/:/app/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_HOST=3.35.81.217
      - ELASTICSEARCH_PORT=9200
    command: sh entrypoint.sh
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - webnet

  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    container_name: collector-app
    volumes:
      - ./collector:/app
      # conf파일을 수정하기 위한 mount
      - /etc/fluent/fluentd.conf:/etc/fluent/fluentd.conf
      # SSH 키 마운트 경로 변경
      - /home/ubuntu/.ssh/teiren-test.pem:/app/teiren-test.pem
    ports:
      - "8088:8088"
    environment:
      - ELASTICSEARCH_HOST=3.35.81.217
      - ELASTICSEARCH_PORT=9200
    depends_on:
      - django
      - nginx
    networks:
      - webnet

networks:
  webnet:
